#!/usr/bin/env node

import { promises as fs } from "node:fs";
import path from "node:path";

const root = process.cwd();
const skillsDir = path.join(root, "skills");
const outputPath = path.join(root, "docs", "SKILLS.md");

async function pathExists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

function parseFrontmatter(markdown, skillName) {
  if (!markdown.startsWith("---\n")) {
    throw new Error(`${skillName}: SKILL.md must start with YAML frontmatter`);
  }

  const end = markdown.indexOf("\n---", 4);
  if (end === -1) {
    throw new Error(`${skillName}: SKILL.md frontmatter is not closed`);
  }

  const frontmatter = markdown.slice(4, end).trim().split(/\r?\n/);
  const result = {};

  for (const line of frontmatter) {
    const match = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!match) {
      continue;
    }

    const [, key, rawValue] = match;
    result[key] = rawValue.replace(/^["']|["']$/g, "").trim();
  }

  if (!result.name) {
    throw new Error(`${skillName}: frontmatter field "name" is required`);
  }

  if (!result.description) {
    throw new Error(`${skillName}: frontmatter field "description" is required`);
  }

  return result;
}

async function readSkills() {
  if (!(await pathExists(skillsDir))) {
    return [];
  }

  const entries = await fs.readdir(skillsDir, { withFileTypes: true });
  const skills = [];

  for (const entry of entries) {
    if (!entry.isDirectory() || entry.name.startsWith(".")) {
      continue;
    }

    const skillPath = path.join(skillsDir, entry.name, "SKILL.md");
    if (!(await pathExists(skillPath))) {
      throw new Error(`${entry.name}: missing SKILL.md`);
    }

    const markdown = await fs.readFile(skillPath, "utf8");
    const frontmatter = parseFrontmatter(markdown, entry.name);
    skills.push({
      directory: entry.name,
      name: frontmatter.name,
      description: frontmatter.description,
    });
  }

  return skills.sort((a, b) => a.name.localeCompare(b.name));
}

function renderCatalog(skills) {
  const lines = [
    "# Skill Catalog",
    "",
    "Generated by `npm run catalog`.",
    "",
  ];

  if (skills.length === 0) {
    lines.push("No skills have been added yet.", "");
    return lines.join("\n");
  }

  lines.push("| Skill | Directory | Description |");
  lines.push("| --- | --- | --- |");

  for (const skill of skills) {
    lines.push(
      `| ${skill.name} | \`skills/${skill.directory}\` | ${skill.description.replaceAll("|", "\\|")} |`,
    );
  }

  lines.push("");
  return lines.join("\n");
}

const skills = await readSkills();
await fs.mkdir(path.dirname(outputPath), { recursive: true });
await fs.writeFile(outputPath, renderCatalog(skills));
console.log(`Wrote ${path.relative(root, outputPath)} with ${skills.length} skill(s).`);
